# Generated by Django 4.0.4 on 2022-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('Date_of_Birth', models.DateField(max_length=8)),
                ('Marks_in_Physics', models.IntegerField()),
                ('Marks_in_Chemistry', models.IntegerField()),
                ('Marks_in_Math', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
        ),
    ]
